### ISSUE TITLE
SQL files have syntax errors

### ISSUE THREAD

**Issue by mlndz28** [mlndz28/simapla#4]

**Comment by emilio93** [comment]
Para `simapla/sqlsDB/views.sql`

Agregar punto y coma al final de esto
https://github.com/mlndz28/simapla/blob/0ad613892fc3baa8b5fa37ad056aa8e9c9a1e1c5/sqlsDB/views.sql#L41

Otro punto y coma al final de esto.
https://github.com/mlndz28/simapla/blob/0ad613892fc3baa8b5fa37ad056aa8e9c9a1e1c5/sqlsDB/views.sql#L75
